id: opecha:P004427
initial_creation_type: ocr
source_metadata:
  id: bdr:W27488
  title: དཔལ་མཁའ་འགྲོ་སྙན་རྒྱུད་ཀྱི་སྒོམ་དོན་གསལ་བར་བྱེད་པ་རྣམ་ཀུན་མཆོག་གི་བདེ་བར་བསྡོམ་པའི་ངེས་གནས
  volume: ''
  author: ''
