id: P004427
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:35.793964
source_metadata:
  id: bdr:W27488
  title: དཔལ་མཁའ་འགྲོ་སྙན་རྒྱུད་ཀྱི་སྒོམ་དོན་གསལ་བར་བྱེད་པ་རྣམ་ཀུན་མཆོག་གི་བདེ་བར་བསྡོམ་པའི་ངེས་གནས
  author: ''
  volumes:
    024dc6576c4c401685c1633449130ff5:
      image_group_id: I4499
      title: ''
      volume_number: 1
      total_pages: 336
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
